import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavBar } from "./components/Navbar";
import Hydrate from "./components/Hydrate";
import { PrimeReactProvider, PrimeReactContext } from 'primereact/api';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sig - Vendas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <Hydrate>
          <NavBar/>
            <PrimeReactProvider>
              <main className="bg-slate-700 h-screen p-20">{children}</main>
            </PrimeReactProvider>
        </Hydrate>
      </body>
    </html>
  );
}
